# Generated by Django 6.1.1 on 2026-09-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('category', models.CharField(choices=[('Tea', 'Tea'), ('Coffee', 'Coffee'), ('Breakfast', 'Breakfast'), ('Snacks', 'Snacks'), ('Cool Drinks', 'Cool Drinks'), ('Specials', 'Specials')], max_length=50)),
                ('tag', models.CharField(blank=True, max_length=50)),
                ('image', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
